---
development: &defaults
    adapter: mysql
    database: ifloat_dev
    host: localhost
    username: ifloat_app
    password: j4hd7ag234

rake:
    <<: *defaults
 
test:
    <<: *defaults
    database: ifloat_test

staging:
    <<: *defaults
    database: ifloat_stag

production:
    <<: *defaults
    database: ifloat_prod
