defaults: &defaults
  adapter: mysql
  host: localhost
  username: ifloat_app
  password: j4hd7ag234
  encoding: utf8
  reconnect: true
  mysql_encoding: utf8
  variables:
    charset: utf8
    collation: utf8_unicode_ci

development:
  <<: *defaults
  database: ifloat_dev

test:
  <<: *defaults
  database: ifloat_test

staging:
  <<: *defaults
  database: ifloat_stag

production:
  <<: *defaults
  database: ifloat_prod

rake:
  <<: *defaults
  database: ifloat_dev